version: "3"

services:
  l2tp:
    build: ./docker
    container_name: l2tp
    privileged: true
    restart: always
    ports:
    - 500:500/udp
    - 4500:4500/udp
    env_file:
    - ./l2tp.env
    volumes:
    - /lib/modules:/lib/modules
    - ./config:/config
